# Generated by Django 3.1.5 on 2021-01-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_hash',
        ),
        migrations.AddField(
            model_name='upload',
            name='hash',
            field=models.TextField(default=None),
        ),
    ]
