# Generated by Django 3.1.5 on 2021-01-23 00:17

import cloud_check_file.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20210123_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='size',
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default=cloud_check_file.core.models.get_default_name_for_file, max_length=255),
        ),
        migrations.AddField(
            model_name='upload',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
